#!/bin/bash

# Define paths
PID_FILE="/var/run/my_process.pid"
LOG_FILE="/tmp/my_process"

start() {
    if [ -f "$PID_FILE" ]; then
        echo "manage_my_process is already running. PID: $(cat $PID_FILE)"
    else
        nohup "$0" background > /dev/null 2>&1 &
        echo $! > "$PID_FILE"
        echo "manage_my_process started. PID: $(cat $PID_FILE)"
    fi
}

stop() {
    if [ -f "$PID_FILE" ]; then
        kill $(cat $PID_FILE)
        rm "$PID_FILE"
        echo "manage_my_process stopped."
    else
        echo "manage_my_process is not running."
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted."
}

background() {
    while true
    do
        echo "I am alive!" >> "$LOG_FILE"
        sleep 2
    done
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    background)
        background
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0

