#!/bin/bash

case "$1" in
    "start")
        if [ -f "/var/run/my_process.pid" ]; then
            echo "Error: manage_my_process is already running."
        else
            echo "I am alive!" > /tmp/my_process &
            echo $! > /var/run/my_process.pid
            echo "manage_my_process started"
        fi
        ;;
    "stop")
        if [ -f "/var/run/my_process.pid" ]; then
            kill -9 $(cat /var/run/my_process.pid)
            rm /var/run/my_process.pid
            echo "manage_my_process stopped"
        else
            echo "Error: manage_my_process is not running."
        fi
        ;;
    "restart")
        if [ -f "/var/run/my_process.pid" ]; then
            kill -9 $(cat /var/run/my_process.pid)
            rm /var/run/my_process.pid
            echo "manage_my_process stopped"
        fi
        echo "I am alive!" > /tmp/my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
